Repository Valentina810/week-planner-for-marusia, pull requests merged in 2024-09, with the labels that each got.

#96 [Аналитика] Добавить удаление события #87
  src/docs/v2 [Аналитика] Добавить удаление события #87 .docx
Labels: analytics

#97 Добавить фильтр входящих запросов по заголовку 'user-agent: MailRu-VC/1.0'
  Dockerfile
  README.md
  pom.xml
  settings.xml
  src/main/java/com/github/valentina810/weekplannerformarusia/config/CurlLoggingFilter.java
Labels: feature, 2.0.0

#99 Добавить тесты для CurlLoggingFilter
  .github/workflows/maven.yml
  src/main/java/com/github/valentina810/weekplannerformarusia/config/CurlLoggingFilter.java
  src/main/java/com/github/valentina810/weekplannerformarusia/util/CachedBodyHttpServletRequest.java
  src/main/java/com/github/valentina810/weekplannerformarusia/util/CurlCommandBuilder.java
  src/test/java/com/github/valentina810/weekplannerformarusia/config/CurlLoggingFilterTest.java
Labels: test

#100 Добавить в приветственное сообщение навыка подробный рассказ о его функциях и командах, добавить в справку инфу о версии
  README.md
  commands.json
  src/test/java/com/github/valentina810/weekplannerformarusia/action/executor/composite/parameterized/hello/HelloTestData.java
  src/test/java/com/github/valentina810/weekplannerformarusia/action/executor/composite/parameterized/help/HelpTestData.java
  src/test/java/com/github/valentina810/weekplannerformarusia/action/executor/composite/parameterized/unknown/ParameterForUnknownTest.java
Labels: feature, 2.0.0

#102 При озвучивании команд дату события озвучивать в виде "понедельник двадцать шестое сентября", если часы во времени содержат ноль впереди, то убрать ноль
  README.md
  commands.json
  src/main/java/com/github/valentina810/weekplannerformarusia/action/executor/composite/BaseExecutor.java
  src/main/java/com/github/valentina810/weekplannerformarusia/action/executor/composite/WeeklyPlanExecutor.java
  src/main/java/com/github/valentina810/weekplannerformarusia/storage/persistent/PersistentStorage.java
  src/main/java/com/github/valentina810/weekplannerformarusia/util/DateConverter.java
  src/main/java/com/github/valentina810/weekplannerformarusia/util/TimeConverter.java
  src/test/java/com/github/valentina810/weekplannerformarusia/action/executor/composite/BaseExecutorTest.java
  src/test/java/com/github/valentina810/weekplannerformarusia/action/executor/composite/addevent/AddEventExecutorTest.java
  src/test/java/com/github/valentina810/weekplannerformarusia/action/executor/composite/parameterized/dayplan/EventsForDateTestData.java
  src/test/java/com/github/valentina810/weekplannerformarusia/action/executor/composite/parameterized/hello/HelloTestData.java
  src/test/java/com/github/valentina810/weekplannerformarusia/action/executor/composite/parameterized/help/HelpTestData.java
  src/test/java/com/github/valentina810/weekplannerformarusia/action/executor/composite/parameterized/weeklyplan/WeeklyPlanTestData.java
  src/test/java/com/github/valentina810/weekplannerformarusia/storage/persistent/PersistentStorageTest.java
  src/test/java/com/github/valentina810/weekplannerformarusia/util/TimeConverterTestData.java
  tokens.json
Labels: feature, 2.0.0
